# Required configuration
language: android
sudo: required
jdk: oraclejdk8

# Add the following lines so that the cache is not always updated
before_cache:
 -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 -rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
 -$HOME/.gradle/caches/
 -$HOME/.gradle/wrapper/
 
 # Set up the environment/global variables to be used in the build
 # ANDROID_API and ANDROID_BUILD_TOOLS must match your 'buld.gradle' file
 env:
 global:
 - ANDROID_API=25
 - EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=25.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes
 
 # Then, the components
 android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+
 
 # Before install
 before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > 
"$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- ./gradlew dependencies || true

# Defines the creation and starting og the Android emulator
before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

# Script
# 'connectedCheck' executes instrumentation tests located in /src/androidTests/
script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
