# Required configuration
language: android
jdk: oraclejdk8

before_install:
 - chmod +x gradlew   # To avoid permission issues

android:
 components:
 - tools
 - build-tools-25.0.0
 - platform-tools
 - android-25
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services

# Script
# 'connectedCheck' executes instrumentation tests located in /src/androidTests/
script:
- ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace
